### ISSUE TITLE
[EPOS] Aktive valg

### ISSUE THREAD

**Issue by Texasslim** [behandlingsoversikt/behov#49]
Som: bruker av Behandlingsoversikt
Ønsker jeg å: ta aktive valg i utfylling av en behandling
Slik at: ikke noen av feltene blir "uvurdert" og dermed "standardverdier"

Lenke til trådskisser: 
Lenke til overordna arkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Mindre viktig

**Comment by RogerSOlsen** [comment]
det var kun en brukerhistorie knyttet til eposet. Den er levert og eposet er derfor lukket
