### ISSUE TITLE
[BRUKERHISTORIE] Aktivt valg ang. artikkel 9 eller 10

### ISSUE THREAD

**Issue by Texasslim** [behandlingsoversikt/behov#50]
Som: bruker av registreringsløsningen / Behandlingsoversikt som registrerer en behandling
Ønsker jeg å: svare ja eller nei på om behandlingen som registreres omfattes av artikkel 9 eller 10 
Slik at: jeg tar et aktivt valg om dette. Dette kan gjøres med radioknapper med ja og nei, hvor ingen av alternativene er forhåndsvalgt.

Relatert til epos: Informasjonsforvaltning/tmp_behandlingsoversikt_behov#49
Relatert brukerhistorie: Informasjonsforvaltning/tmp_behandlingsoversikt_behov#11

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

**Comment by RogerSOlsen** [comment]
brukerhistorien er levert og er derfor lukket
