### ISSUE TITLE
[BRUKERHISTORIE] Slette behandlingsaktivitet

### ISSUE THREAD

**Issue by marittor** [behandlingsoversikt/behov#65]
Som: skrivebruker/admin?
Ønsker jeg å: kunne slette/fjerne oppføringer av behandlingsaktiviteter som ikke har vært publisert
Slik at: jeg slipper å navigere i behandlingsaktiviteter som aldri skulle vært registrert.

Relatert til epos: Informasjonsforvaltning/tmp_behandlingsoversikt_behov#68 

Trådskisser: Mangler
Lenke til design:  https://invis.io/APUPOL4B4G7#/395862839_BEHAKT-REG-Overforing-Input-Godkjent--D-

Lenke til løsningsarkitektur: se epos

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Foreløpig - Mindre viktig

Akseptansekriterier:
- [x] Sjekk at godkjente aktiviteter ikke kan slettes
- [x] Sjekk at utkast-aktiviteter kan slettes
- [x] Verifiser at det blir gitt tilstrekkelig advarsler når en bruker velger slett

**Comment by RogerSOlsen** [comment]
Lukkes! man får opp melding "Er du sikker du vil slette denne behandlingsaktiviteten?" når man klikker på "Slett"
