### ISSUE TITLE
[EPOS] Protokoll over behandlingsaktiviteter grunnleggende

### ISSUE THREAD

**Issue by data-david** [behandlingsoversikt/behov#68]
Etter initiativ fra Difi og Skatteetaten har vi sett på muligheten til å tilpasse felles datakatalog slik at det også kan brukes som et verktøy for å oppfylle kravene i den nye personopplysningsloven om å føre protokoll over behandlingsaktiviteter (artikkel 30). Hypotesen var at dette kunne løses med å legge til noen felter i beskrivelsen av datasett i felles datakatalog. Vi har kommet frem til at behovet dekkes best ved å legge til mulighet for å registrere det som er kjernen i protokollen, nemlig behandlingsaktiviteter. Ved å registrere behandlingsaktiviteter som del av felles datakatalog, får virksomhetene synergieffekter av beskrivelser som finnes allerede, eller legges til senere, av datasett, begrep, informasjonsmodeller m.m.

[Beskrivelse av behovet med designskisser] (https://drive.google.com/drive/folders/1blOJa8zHtidtk1nWAZKoIDFi6UmFNiWJ)

Lenke til løsningsarkitektur: https://informasjonsforvaltning.github.io/SA_Informasjonsforvaltning/f4212a30-53d0-4c27-a682-4f88d6c692c8/views/5c18f1ba-7be9-4a83-b2b1-1ae505662eb4.html
PS! Beskrivelse av løsningsarkitektur er minimalistisk, men oppsummert går det ut på å lage same type løysing som concept-catalogue/concept-catalogue-gui _uten_ høste-endepunkt. Gjetter at mongodb er grei lagringsmekanisme, men er åpen for forslag.

**Comment by RogerSOlsen** [comment]
Samtlige brukerhistorier som var knyttet til eposet er levert. Eposet er derfor lukket
